#!/usr/bin/env python3
"""Run NotebookLM validation batches generated by the all-response builder."""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_ID = "bb37eb1a-3b19-4f6c-9cc3-7df3a41e1388"
BATCHES = ROOT / "data" / "extraction" / "all_responses" / "NOTEBOOKLM_VALIDATION_BATCHES.csv"
OUT_DIR = ROOT / "data" / "extraction" / "all_responses" / "notebooklm_validation"
RUN_LOG = ROOT / "data" / "extraction" / "all_responses" / "NOTEBOOKLM_VALIDATION_RUN_LOG.csv"
SUMMARY = ROOT / "data" / "extraction" / "all_responses" / "NOTEBOOKLM_VALIDATION_SUMMARY.md"


RUN_LOG_FIELDS = [
    "batch_id",
    "response_type",
    "source_count",
    "status",
    "returncode",
    "started_at_utc",
    "ended_at_utc",
    "elapsed_seconds",
    "output_json",
    "answer_chars",
    "sources_used_count",
    "stderr",
]


def validation_prompt(response_type: str) -> str:
    return (
        f"Validate the extraction scaffold for these coral regeneration {response_type} sources. "
        "For each source you can read, return one compact row with: source_id; "
        "response variables measured; taxon; wound/fragment/colony size information; "
        "timepoints or monitoring duration; sample size and variance if reported; "
        "environmental setting; experimental treatments or stressors; and key missing covariates. "
        "Use only the restricted sources and cite evidence numbers."
    )


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def relpath(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def parse_answer_stats(output_path: Path) -> tuple[int, int]:
    if not output_path.exists():
        return 0, 0
    try:
        payload = json.loads(output_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return 0, 0
    answer = ""
    sources_used = []
    if isinstance(payload, dict):
        result = payload.get("result", payload)
        if isinstance(result, dict):
            answer = str(result.get("answer", ""))
            sources_used = result.get("sources_used", []) or []
        else:
            answer = str(payload.get("answer", ""))
            sources_used = payload.get("sources_used", []) or []
    return len(answer), len(sources_used)


def run_batch(batch: dict[str, str], args: argparse.Namespace) -> dict[str, object]:
    batch_id = batch["batch_id"]
    output_path = args.output_dir / f"{batch_id}.json"
    if output_path.exists() and not args.force:
        answer_chars, sources_used_count = parse_answer_stats(output_path)
        return {
            "batch_id": batch_id,
            "response_type": batch.get("response_type", ""),
            "source_count": batch.get("source_count", ""),
            "status": "skipped_existing",
            "returncode": "",
            "started_at_utc": "",
            "ended_at_utc": "",
            "elapsed_seconds": "",
            "output_json": relpath(output_path),
            "answer_chars": answer_chars,
            "sources_used_count": sources_used_count,
            "stderr": "",
        }

    source_ids = ",".join(batch.get("source_ids", "").split("|"))
    prompt = batch.get("query_prompt", "")
    if args.prompt_mode == "audit":
        prompt = validation_prompt(batch.get("response_type", ""))

    cmd = [
        "nlm",
        "notebook",
        "query",
        "--json",
        "--source-ids",
        source_ids,
        "--timeout",
        str(args.query_timeout),
        args.notebook_id,
        prompt,
    ]
    started = utc_now()
    start_time = time.monotonic()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    try:
        proc = subprocess.run(
            cmd,
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
            timeout=args.process_timeout,
        )
        status = "completed" if proc.returncode == 0 else "failed"
        output_path.write_text(proc.stdout, encoding="utf-8")
        stderr = " ".join(proc.stderr.split())[:500]
        returncode = proc.returncode
    except subprocess.TimeoutExpired as exc:
        status = "timeout"
        output_path.write_text(exc.stdout or "", encoding="utf-8")
        stderr = " ".join(str(exc).split())[:500]
        returncode = 124
    elapsed = time.monotonic() - start_time
    ended = utc_now()
    answer_chars, sources_used_count = parse_answer_stats(output_path)
    return {
        "batch_id": batch_id,
        "response_type": batch.get("response_type", ""),
        "source_count": batch.get("source_count", ""),
        "status": status,
        "returncode": returncode,
        "started_at_utc": started,
        "ended_at_utc": ended,
        "elapsed_seconds": f"{elapsed:.1f}",
        "output_json": relpath(output_path),
        "answer_chars": answer_chars,
        "sources_used_count": sources_used_count,
        "stderr": stderr,
    }


def write_summary(path: Path, rows: list[dict[str, object]]) -> None:
    status_counts: dict[str, int] = {}
    for row in rows:
        status_counts[str(row.get("status", ""))] = status_counts.get(str(row.get("status", "")), 0) + 1

    def as_int(value: object) -> int:
        try:
            return int(value or 0)
        except (TypeError, ValueError):
            return 0

    valid_json = 0
    source_checks = 0
    cited_source_checks = 0
    answer_chars = 0
    for row in rows:
        source_checks += as_int(row.get("source_count", ""))
        sources_used = as_int(row.get("sources_used_count", ""))
        cited_source_checks += sources_used
        chars = as_int(row.get("answer_chars", ""))
        answer_chars += chars
        if chars > 0 and sources_used > 0:
            valid_json += 1
    lines = [
        "# NotebookLM Validation Summary",
        "",
        "Generated by `python3 tools/run_notebooklm_validation_batches.py`.",
        "",
        f"- batches logged: {len(rows)}",
        f"- batch JSON files with answers and cited sources: {valid_json}",
        f"- response-specific source checks requested: {source_checks}",
        f"- response-specific source checks cited by NotebookLM: {cited_source_checks}",
        f"- total answer characters: {answer_chars}",
    ]
    for status, count in sorted(status_counts.items()):
        lines.append(f"- `{status}`: {count}")
    lines.extend(
        [
            "",
            "## Files",
            "",
            f"- `{relpath(RUN_LOG)}`",
            f"- `{relpath(OUT_DIR)}/<batch_id>.json`",
            "",
            "## Interpretation",
            "",
            "- These NotebookLM outputs are independent checks on PDF-derived extraction targets.",
            "- `skipped_existing` means a prior valid JSON output was reused, not that the source was unvalidated.",
            "- Treat NotebookLM values as candidate validations, not final pooled data, until direct PDF/table/figure provenance is recorded.",
            "- Re-run failed or timed-out batches with `--force --batch-id <id>`.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batches", type=Path, default=BATCHES)
    parser.add_argument("--output-dir", type=Path, default=OUT_DIR)
    parser.add_argument("--run-log", type=Path, default=RUN_LOG)
    parser.add_argument("--summary", type=Path, default=SUMMARY)
    parser.add_argument("--notebook-id", default=NOTEBOOK_ID)
    parser.add_argument("--batch-id", action="append", default=[])
    parser.add_argument("--query-timeout", type=float, default=120.0)
    parser.add_argument("--process-timeout", type=float, default=180.0)
    parser.add_argument("--prompt-mode", choices=["audit", "csv"], default="audit")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    batches = read_csv(args.batches)
    if args.batch_id:
        wanted = set(args.batch_id)
        batches = [batch for batch in batches if batch.get("batch_id") in wanted]
    rows = [run_batch(batch, args) for batch in batches]
    write_csv(args.run_log, RUN_LOG_FIELDS, rows)
    write_summary(args.summary, rows)
    failed = [row for row in rows if row.get("status") in {"failed", "timeout"}]
    print(f"Wrote {relpath(args.summary)}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
